### ISSUE TITLE
Illegal moves cause segmentation fault

### ISSUE THREAD

**Issue by salamanderrake** [jdart1/arasan-chess#3]
Trying to test the error output for Arasan in the terminal and its causing a segmentation fault.
This is with 17.5 release linux binaries.

I tried it with e1
here is the output I get from gdb

```
gdb ./arasanx-64
GNU gdb (GDB; openSUSE 13.2) 7.8
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...

warning: /etc/gdbinit.d/gdb-heap.py: No such file or directory
/home/salamanderrake/.gdbinit:1: Error in sourced command file:
No symbol table is loaded.  Use the "file" command.
Reading symbols from ./arasanx-64...(no debugging symbols found)...done.
(gdb) set args  -H 100M -c 2
(gdb) r
Starting program: /mnt/store/ChessBoard/ThirdParty/Arasan/arasanx-64 -H 100M -c 2
Got object file from memory but can't read symbols: File truncated.
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.19-16.12.1.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Arasan 17.5 Copyright 1994-2015 by Jon Dart. All Rights Reserved.
[New Thread 0x7ffff6ff7700 (LWP 11506)]
[New Thread 0x7ffff61c6700 (LWP 11507)]
e1e6

Program received signal SIGSEGV, Segmentation fault.
0x000000000042d98f in Board::calcAttacks(int, ColorType) const ()
Missing separate debuginfos, use: zypper install libgcc_s1-debuginfo-4.8.3+r212056-2.2.4.x86_64 libstdc++6-debuginfo-4.8.3+r212056-2.2.4.x86_64
(gdb) bt all
No symbol table is loaded.  Use the "file" command.
(gdb) bt
#0  0x000000000042d98f in Board::calcAttacks(int, ColorType) const ()
#1  0x000000000045bae2 in MoveGenerator::generateEvasionsCaptures(unsigned long long*) ()
#2  0x000000000045bfa2 in MoveGenerator::nextEvasion() ()
#3  0x0000000000452922 in Search::search() ()
#4  0x0000000000454e4d in RootSearch::ply0_search(RootMoveGenerator&, int, int, int, int, unsigned long long*, int) ()
#5  0x0000000000455bc8 in RootSearch::ply0_search(unsigned long long*, int) ()
#6  0x0000000000457155 in SearchController::findBestMove(Board const&, SearchType, int, int, int, int, int, Statistics&, TalkLevel, unsigned long long*, int) ()
#7  0x000000000045721d in SearchController::findBestMove(Board const&, SearchType, int, int, int, int, int, Statistics&, TalkLevel) ()
#8  0x0000000000405c8e in search(SearchController*, Board&, Statistics&, bool) [clone .constprop.100] ()
#9  0x00000000004253c4 in do_command(std::string const&, Board&) ()
#10 0x00000000004079ed in main ()

```

The funny thing is it works fine with xboard when I make an Illegal move.

**Comment by jdart1** [comment]
It works with xboard because xboard itself validates moves. I'm probably not going to fix this since it should not show up in normal usage.
